#!/bin/sh

g++ -g -I../inc/ $1\
	../src/atoms.cpp\
	../src/executors.cpp\
	../src/heaps.cpp\
	../src/processes.cpp\
	../src/phandles.cpp\
	../src/runsystems.cpp\
	../src/types.cpp\
	../src/variables.cpp

